# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misfitapp', '0005_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text=b"The profile's user", on_delete=django.db.models.deletion.CASCADE, related_name='misfit_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
